# Generated by Django 4.2.7 on 2025-07-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Método de Pago')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('partial', 'Parcial')], default='pending', max_length=10, verbose_name='Estado')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Contrato')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contratos',
                'ordering': ['-due_date'],
            },
        ),
    ]
