# Generated by Django 4.2.7 on 2025-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía'),
        ),
    ]
