# Generated by Django 4.2.7 on 2025-07-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='commission_rate',
        ),
    ]
