# Generated by Django 4.2.7 on 2025-08-01 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('agents', '0003_remove_agent_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'unique_together': {('content_type', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de Sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.JSONField(default=dict, verbose_name='Información del Dispositivo')),
                ('location', models.JSONField(default=dict, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=50, verbose_name='Zona Horaria')),
                ('language', models.CharField(default='es', max_length=5, verbose_name='Idioma')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Teléfono Verificado')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Habilitado')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('backup_codes', models.JSONField(default=list, verbose_name='Códigos de Respaldo')),
                ('profile_completion', models.IntegerField(default=0, verbose_name='Completitud del Perfil (%)')),
                ('last_profile_update', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_attempts', models.IntegerField(default=0, verbose_name='Intentos de Login')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Contraseña Cambiada')),
                ('require_password_change', models.BooleanField(default=False, verbose_name='Requiere Cambio de Contraseña')),
                ('allowed_ip_addresses', models.JSONField(default=list, verbose_name='IPs Permitidas')),
                ('suspicious_activity_alerts', models.BooleanField(default=True, verbose_name='Alertas de Actividad Sospechosa')),
                ('session_timeout_minutes', models.IntegerField(default=480, verbose_name='Timeout de Sesión (minutos)')),
                ('last_password_reset', models.DateTimeField(blank=True, null=True, verbose_name='Último Reset de Contraseña')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='Rol del Sistema')),
                ('agents', models.ManyToManyField(related_name='roles', through='agents.AgentRole', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, to='agents.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='agentrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.role'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('password_change', 'Cambio de Contraseña'), ('profile_update', 'Actualización de Perfil'), ('role_assigned', 'Rol Asignado'), ('permission_granted', 'Permiso Otorgado'), ('data_export', 'Exportación de Datos'), ('security_settings_change', 'Cambio de Configuración de Seguridad'), ('suspicious_activity', 'Actividad Sospechosa'), ('account_locked', 'Cuenta Bloqueada'), ('account_unlocked', 'Cuenta Desbloqueada'), ('2fa_enabled', '2FA Habilitado'), ('2fa_disabled', '2FA Deshabilitado')], max_length=100, verbose_name='Acción')),
                ('resource_type', models.CharField(max_length=50, verbose_name='Tipo de Recurso')),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Recurso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('details', models.JSONField(default=dict, verbose_name='Detalles')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave de Sesión')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'action'], name='agents_audi_agent_i_4c5e05_idx'), models.Index(fields=['created_at'], name='agents_audi_created_75b1f3_idx'), models.Index(fields=['ip_address'], name='agents_audi_ip_addr_945a57_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='agentrole',
            unique_together={('agent', 'role')},
        ),
    ]
