# Generated by Django 4.2.7 on 2025-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentrole_permission_usersession_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira Token Reset'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Reset'),
        ),
    ]
