# Generated by Django 4.2.7 on 2025-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la empresa', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Dirección de la empresa', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de la empresa', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Sitio web de la empresa', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logotipo de la empresa', null=True, upload_to='logos/')),
                ('tax_id', models.CharField(blank=True, help_text='NIF/CIF de la empresa', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
    ]
