# Generated by Django 4.2.7 on 2025-07-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='EUR', help_text='Código de moneda (ISO 4217)', max_length=3)),
                ('timezone', models.CharField(default='Europe/Madrid', help_text='Zona horaria del sistema', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', help_text='Formato de fecha', max_length=20)),
                ('language', models.CharField(default='es', help_text='Idioma del sistema', max_length=5)),
                ('decimal_places', models.IntegerField(default=2, help_text='Decimales para moneda')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, help_text='Tasa de impuesto por defecto (%)', max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefijo para facturas', max_length=10)),
                ('contract_prefix', models.CharField(default='CON', help_text='Prefijo para contratos', max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_config', to='core.company')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Recordatorio de Pago'), ('contract_expiry', 'Vencimiento de Contrato'), ('maintenance_due', 'Mantenimiento Pendiente'), ('new_inquiry', 'Nueva Consulta'), ('document_ready', 'Documento Listo'), ('system_alert', 'Alerta del Sistema')], help_text='Tipo de notificación', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Notificación habilitada')),
                ('email_template', models.TextField(blank=True, help_text='Plantilla de email', null=True)),
                ('frequency_days', models.IntegerField(default=1, help_text='Frecuencia en días')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.company')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'unique_together': {('company', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Nombre de la plantilla', max_length=100)),
                ('template_type', models.CharField(choices=[('invoice', 'Factura'), ('contract', 'Contrato'), ('receipt', 'Recibo'), ('report', 'Reporte'), ('email', 'Email'), ('letter', 'Carta')], help_text='Tipo de documento', max_length=50)),
                ('header_content', models.TextField(blank=True, help_text='Contenido del encabezado', null=True)),
                ('footer_content', models.TextField(blank=True, help_text='Contenido del pie de página', null=True)),
                ('custom_css', models.TextField(blank=True, help_text='CSS personalizado', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Plantilla activa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'unique_together': {('company', 'template_name', 'template_type')},
            },
        ),
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_key', models.CharField(help_text='Clave de configuración', max_length=100)),
                ('config_value', models.TextField(blank=True, help_text='Valor de configuración', null=True)),
                ('config_type', models.CharField(choices=[('string', 'Texto'), ('boolean', 'Verdadero/Falso'), ('integer', 'Número Entero'), ('decimal', 'Número Decimal'), ('json', 'Objeto JSON'), ('file', 'Archivo')], default='string', help_text='Tipo de dato', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='core.company')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
                'unique_together': {('company', 'config_key')},
            },
        ),
    ]
