# Generated by Django 4.2.7 on 2025-07-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemconfiguration_notificationsettings_and_more'),
    ]

    operations = [
    ]
