# Generated by Django 4.2.7 on 2025-07-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('sale', 'Venta'), ('rental', 'Alquiler')], max_length=10, verbose_name='Tipo de Contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='ARS', max_length=10, verbose_name='Moneda')),
                ('terms', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
            },
        ),
        migrations.CreateModel(
            name='ContractIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Anterior')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nuevo Monto')),
                ('increase_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Aumento')),
                ('effective_date', models.DateField(verbose_name='Fecha Efectiva')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increases', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Aumento de Contrato',
                'verbose_name_plural': 'Aumentos de Contratos',
                'ordering': ['-effective_date'],
            },
        ),
    ]
