# Generated by Django 4.2.7 on 2025-07-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('expiring_soon', 'Próximo a Vencer'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado del Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el contrato está activo', verbose_name='Activo'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
