# Generated by Django 4.2.7 on 2025-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_invoiceitem_invoice_contract_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi-annually', 'Semestral'), ('annually', 'Anual')], max_length=20, null=True, verbose_name='Frecuencia de Aumento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Aumento'),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_increase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Próximo Aumento'),
        ),
    ]
