# Generated by Django 4.2.7 on 2025-07-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_contract_type_contract_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('increase_reminder', 'Recordatorio de Aumento'), ('increase_applied', 'Aumento Aplicado'), ('contract_expiring', 'Contrato Por Vencer')], max_length=20, verbose_name='Tipo de Notificación')),
                ('notification_date', models.DateField(verbose_name='Fecha de Notificación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('dismissed', 'Descartada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Notificación de Contrato',
                'verbose_name_plural': 'Notificaciones de Contratos',
                'ordering': ['-notification_date'],
            },
        ),
    ]
