# Generated by Django 4.2.7 on 2025-07-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractNotification',
        ),
    ]
