# Generated by Django 4.2.7 on 2025-07-24 16:30

from django.db import migrations, models
from django.utils import timezone


def update_expiring_soon_contracts(apps, schema_editor):
    """
    Actualiza los contratos que tienen estado 'expiring_soon' para determinar
    su nuevo estado basándose en las fechas actuales.
    """
    Contract = apps.get_model('contracts', 'Contract')
    today = timezone.now().date()
    
    # Obtener todos los contratos con estado 'expiring_soon'
    expiring_contracts = Contract.objects.filter(status='expiring_soon')
    
    for contract in expiring_contracts:
        # Determinar el nuevo estado basándose en las fechas
        if contract.end_date and today > contract.end_date:
            # Si ya pasó la fecha de fin, finalizar el contrato
            contract.status = 'finished'
            contract.is_active = False
        elif contract.start_date <= today and (not contract.end_date or today <= contract.end_date):
            # Si está en el período activo, marcar como activo
            contract.status = 'active'
            contract.is_active = True
        else:
            # En cualquier otro caso, marcar como borrador
            contract.status = 'draft'
        
        contract.save()


def reverse_update_expiring_soon_contracts(apps, schema_editor):
    """
    Función de reversión - no hace nada ya que no podemos recuperar
    el estado anterior de manera confiable.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_delete_contractnotification'),
    ]

    operations = [
        # Primero actualizar los contratos existentes
        migrations.RunPython(
            update_expiring_soon_contracts,
            reverse_update_expiring_soon_contracts
        ),
        # Luego cambiar las opciones del campo
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Borrador'), 
                    ('active', 'Activo'), 
                    ('finished', 'Finalizado'), 
                    ('cancelled', 'Cancelado')
                ], 
                default='draft', 
                max_length=20, 
                verbose_name='Estado del Contrato'
            ),
        ),
    ]
