# Generated by Django 4.2.7 on 2025-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_expiring_soon_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['property', 'status'], name='contracts_c_propert_c81e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['customer', 'status'], name='contracts_c_custome_791003_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['agent', 'status'], name='contracts_c_agent_i_d94443_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['next_increase_date'], name='contracts_c_next_in_8cea51_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_active', 'status'], name='contracts_c_is_acti_4c0776_idx'),
        ),
        migrations.AddIndex(
            model_name='contractincrease',
            index=models.Index(fields=['contract', 'effective_date'], name='contracts_c_contrac_5a56f1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractincrease',
            index=models.Index(fields=['effective_date'], name='contracts_c_effecti_d27014_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('property', 'customer', 'start_date'), name='unique_property_customer_start_date', violation_error_message='Ya existe un contrato para esta propiedad y cliente en la misma fecha de inicio.'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_amount', violation_error_message='El monto del contrato debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='end_date_after_start_date', violation_error_message='La fecha de fin debe ser posterior a la fecha de inicio.'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('increase_percentage__isnull', True), models.Q(('increase_percentage__gte', -100), ('increase_percentage__lte', 1000)), _connector='OR'), name='reasonable_increase_percentage', violation_error_message='El porcentaje de aumento debe estar entre -100% y 1000%.'),
        ),
        migrations.AddConstraint(
            model_name='contractincrease',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_date'), name='unique_contract_increase_date', violation_error_message='Ya existe un aumento para este contrato en la misma fecha.'),
        ),
        migrations.AddConstraint(
            model_name='contractincrease',
            constraint=models.CheckConstraint(check=models.Q(('previous_amount__gt', 0)), name='positive_previous_amount', violation_error_message='El monto anterior debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='contractincrease',
            constraint=models.CheckConstraint(check=models.Q(('new_amount__gt', 0)), name='positive_new_amount', violation_error_message='El nuevo monto debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='contractincrease',
            constraint=models.CheckConstraint(check=models.Q(('increase_percentage__gte', -100), ('increase_percentage__lte', 1000)), name='reasonable_increase_percentage_range', violation_error_message='El porcentaje de aumento debe estar entre -100% y 1000%.'),
        ),
    ]
