# Generated by Django 4.2.7 on 2025-07-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_add_validations_and_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='reasonable_increase_percentage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='increase_percentage',
        ),
    ]
