# Generated by Django 4.2.7 on 2025-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_remove_contract_reasonable_increase_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje que se descontará al propietario (0-100%)', max_digits=5, null=True, verbose_name='Porcentaje de Descuento al Propietario (%)'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('owner_discount_percentage__isnull', True), models.Q(('owner_discount_percentage__gte', 0), ('owner_discount_percentage__lte', 100)), _connector='OR'), name='valid_owner_discount_percentage', violation_error_message='El porcentaje de descuento debe estar entre 0% y 100%.'),
        ),
    ]
