# Generated by Django 4.2.7 on 2025-07-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Característica')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('street', models.CharField(max_length=200, verbose_name='Calle')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('locality', models.CharField(max_length=100, verbose_name='Localidad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('total_surface', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie Total (m²)')),
                ('covered_surface', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Cubierta (m²)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Dormitorios')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('garage', models.BooleanField(default=False, verbose_name='Garage')),
                ('furnished', models.BooleanField(default=False, verbose_name='Amueblado')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Alquiler')),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Expensas')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Construcción')),
                ('orientation', models.CharField(blank=True, max_length=50, verbose_name='Orientación')),
                ('floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plantas')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('features', models.ManyToManyField(blank=True, to='properties.feature', verbose_name='Características')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Propiedad',
                'verbose_name_plural': 'Estados de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiqueta')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagen')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagen de Portada')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertystatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, to='properties.tag', verbose_name='Etiquetas'),
        ),
    ]
