# Generated by Django 4.2.7 on 2025-07-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_country_alter_customer_locality_and_more'),
        ('properties', '0002_property_owner_alter_property_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Dueño'),
        ),
    ]
