# Generated by Django 4.2.7 on 2025-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Alquiler'), ('sale', 'Venta'), ('both', 'Alquiler y Venta')], default='sale', max_length=10, verbose_name='Tipo de Listado'),
        ),
    ]
