# Generated by Django 4.2.7 on 2025-07-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_transfer_to_accounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
