# Generated by Django 4.2.7 on 2025-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Calle')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profesión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
