# Generated by Django 4.2.7 on 2025-07-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leído")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("invoice_due_soon", "Vencimiento Próximo"),
                            ("invoice_overdue", "Factura Vencida"),
                            ("invoice_payment_received", "Pago Recibido"),
                            ("invoice_status_change", "Cambio de Estado"),
                            ("contract_increase", "Aumento de Contrato"),
                            ("generic", "Notificación General"),
                        ],
                        default="generic",
                        max_length=30,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
