# Generated by Django 4.2.7 on 2025-07-16 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receive_invoice_due_soon', models.BooleanField(default=True, verbose_name='Recibir notificaciones de facturas por vencer')),
                ('receive_invoice_overdue', models.BooleanField(default=True, verbose_name='Recibir notificaciones de facturas vencidas')),
                ('receive_invoice_payment', models.BooleanField(default=True, verbose_name='Recibir notificaciones de pagos de facturas')),
                ('receive_invoice_status_change', models.BooleanField(default=True, verbose_name='Recibir notificaciones de cambios de estado de facturas')),
                ('notification_frequency', models.CharField(choices=[('immediately', 'Inmediatamente'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente')], default='immediately', max_length=20, verbose_name='Frecuencia de notificaciones')),
                ('days_before_due_date', models.PositiveIntegerField(default=7, verbose_name='Días de anticipación para notificar vencimientos')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Recibir notificaciones por correo electrónico')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificaciones',
            },
        ),
    ]
