# Generated by Django 4.2.7 on 2025-08-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_due_soon', 'Vencimiento Próximo'), ('invoice_overdue', 'Factura Vencida'), ('invoice_payment_received', 'Pago Recibido'), ('invoice_status_change', 'Cambio de Estado'), ('contract_increase', 'Aumento de Contrato'), ('contract_expiration', 'Vencimiento de Contrato'), ('batch_summary', 'Resumen de Notificaciones'), ('generic', 'Notificación General')], default='generic', max_length=30, verbose_name='Tipo de Notificación'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=30, verbose_name='Tipo de Notificación')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Objeto')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'indexes': [models.Index(fields=['agent', 'notification_type', 'created_date'], name='user_notifi_agent_i_2754b7_idx'), models.Index(fields=['content_type', 'object_id'], name='user_notifi_content_89559f_idx')],
                'unique_together': {('agent', 'notification_type', 'object_id', 'content_type', 'created_date')},
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_type', models.CharField(choices=[('daily', 'Daily Batch'), ('weekly', 'Weekly Batch')], max_length=10, verbose_name='Tipo de Lote')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(max_length=30, verbose_name='Tipo de Notificación')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(verbose_name='Programado para')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Lote de Notificación',
                'verbose_name_plural': 'Lotes de Notificaciones',
                'ordering': ['scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['agent', 'batch_type', 'processed'], name='user_notifi_agent_i_91e90c_idx'), models.Index(fields=['scheduled_for', 'processed'], name='user_notifi_schedul_4f6b72_idx')],
            },
        ),
    ]
