# Generated by Django 4.2.7 on 2025-08-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0003_add_notification_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='receive_contract_expiration',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones de vencimiento de contratos'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='receive_rent_increase',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones de aumentos de alquiler'),
        ),
    ]
