# Generated by Django 4.2.7 on 2025-07-08 18:46

import accounting.models_invoice
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalposition',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='fiscal_position',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'verbose_name': 'Línea de Factura', 'verbose_name_plural': 'Líneas de Factura'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_untaxed',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='move_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='analytic_account',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='date_maturity',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='move',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='price_subtotal',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='concept',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=16),
        ),
        migrations.DeleteModel(
            name='AnalyticAccount',
        ),
        migrations.DeleteModel(
            name='FiscalPosition',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
