# Generated by Django 4.2.7 on 2025-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_invoice_customer_alter_invoice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='property',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
