# Generated by Django 4.2.7 on 2025-07-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_contract_type_contract_frequency_and_more'),
        ('accounting', '0005_remove_invoice_contract_remove_invoice_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract', verbose_name='Contrato'),
        ),
    ]
