# Generated by Django 4.2.7 on 2025-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_invoice_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='state',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=16),
        ),
    ]
