# Generated by Django 4.2.7 on 2025-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_invoice_state_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('validated', 'Validada'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=16),
        ),
    ]
