# Generated by Django 4.2.7 on 2025-07-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_country_alter_customer_locality_and_more'),
        ('accounting', '0008_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('due_soon', 'Vencimiento Próximo'), ('overdue', 'Factura Vencida'), ('payment_received', 'Pago Recibido'), ('status_change', 'Cambio de Estado')], max_length=20)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_notifications', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'Notificación de Factura',
                'verbose_name_plural': 'Notificaciones de Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
