# Generated by Django 4.2.7 on 2025-07-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_invoicenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoicenotification',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoicenotification',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='company',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountTag',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='InvoiceNotification',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
