# Generated by Django 4.2.7 on 2025-08-25 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0010_remove_company_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Comprobante')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('email_sent_to', models.EmailField(max_length=254, verbose_name='Email Enviado a')),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Archivo PDF')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Bruto')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de Descuento')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Neto')),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('sent', 'Enviado'), ('failed', 'Error en envío')], default='generated', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_receipts', to='accounting.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Comprobante de Propietario',
                'verbose_name_plural': 'Comprobantes de Propietarios',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='accounting__invoice_60d8f2_idx'), models.Index(fields=['generated_at'], name='accounting__generat_63db1e_idx'), models.Index(fields=['status'], name='accounting__status_7c4cc9_idx'), models.Index(fields=['receipt_number'], name='accounting__receipt_08bd8c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ownerreceipt',
            constraint=models.CheckConstraint(check=models.Q(('gross_amount__gt', 0)), name='positive_gross_amount', violation_error_message='El monto bruto debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='ownerreceipt',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='non_negative_discount_amount', violation_error_message='El monto de descuento no puede ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='ownerreceipt',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', 0)), name='non_negative_net_amount', violation_error_message='El monto neto no puede ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='ownerreceipt',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__isnull', True), models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), _connector='OR'), name='valid_discount_percentage', violation_error_message='El porcentaje de descuento debe estar entre 0% y 100%.'),
        ),
    ]
