# Generated by Django 4.2.7 on 2025-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_ownerreceipt_ownerreceipt_positive_gross_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Comprobante'),
        ),
    ]
